### ISSUE TITLE
Záporné teploty se zobrazují chybně

### ISSUE THREAD

**Issue by jzobac** [joysfera/arduino-water-temp-receiver#1]
Zdravim,
v kódu máte chybu, pokud teplota začíná na 1111 (12bit číslo; např. pro -1 =  1111 1111 0110) musí se provést doplněk (two complement). Můžete to do kódu přidat? Mělo by to být v souboru WaterTempReceiver.cpp po řádku 134. Mě se to nějak nedaří.

Díky Radius

**Comment by jzobac** [comment]
Poslány 2 patche s úpravou.

Radius

**Comment by joysfera** [comment]
Díky, úpravy jsem zapracoval.
